# Generated by Django 3.1.3 on 2023-03-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inescto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True)),
                ('nomCientifico', models.TextField(blank=True)),
                ('descripcion', models.TextField(blank=True)),
                ('lugar', models.TextField(blank=True)),
                ('venenoso', models.TextField(blank=True)),
                ('habitat', models.TextField(blank=True)),
                ('tamano', models.TextField(blank=True)),
                ('edad', models.TextField(blank=True)),
                ('temporadas', models.TextField(blank=True)),
                ('clasificacion', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Link',
        ),
    ]
