# Generated by Django 3.1.3 on 2023-03-14 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insectos', '0002_auto_20230303_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inescto',
            old_name='clasificacion',
            new_name='clase',
        ),
        migrations.RenameField(
            model_name='inescto',
            old_name='descripcion',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='inescto',
            old_name='edad',
            new_name='dieta',
        ),
        migrations.RenameField(
            model_name='inescto',
            old_name='lugar',
            new_name='familia',
        ),
        migrations.RenameField(
            model_name='inescto',
            old_name='nomCientifico',
            new_name='longitud',
        ),
        migrations.RenameField(
            model_name='inescto',
            old_name='tamano',
            new_name='nom_alas',
        ),
        migrations.RenameField(
            model_name='inescto',
            old_name='venenoso',
            new_name='nom_cientifico',
        ),
        migrations.RenameField(
            model_name='inescto',
            old_name='temporadas',
            new_name='orden',
        ),
    ]
