# Generated by Django 3.1.3 on 2023-03-14 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insectos', '0003_auto_20230314_1430'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inescto',
            new_name='Insecto',
        ),
    ]
