# Generated by Django 3.1.3 on 2023-04-11 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insectos', '0004_auto_20230314_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insecto',
            old_name='nom_alas',
            new_name='nomcientifico',
        ),
        migrations.RenameField(
            model_name='insecto',
            old_name='nom_cientifico',
            new_name='numalas',
        ),
    ]
