# Generated by Django 3.1.3 on 2023-05-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insectos', '0007_auto_20230411_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insecto',
            name='clase',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='insecto',
            name='color',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='insecto',
            name='dieta',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='insecto',
            name='familia',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='insecto',
            name='habitat',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='insecto',
            name='longitud',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='insecto',
            name='nombre',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='insecto',
            name='nomcientifico',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='insecto',
            name='numalas',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='insecto',
            name='orden',
            field=models.TextField(default=''),
        ),
    ]
