# Generated by Django 3.1.3 on 2023-05-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insectos', '0008_auto_20230501_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insecto',
            name='clase',
            field=models.TextField(default='_'),
        ),
        migrations.AlterField(
            model_name='insecto',
            name='color',
            field=models.TextField(default='_'),
        ),
        migrations.AlterField(
            model_name='insecto',
            name='dieta',
            field=models.TextField(default='_'),
        ),
        migrations.AlterField(
            model_name='insecto',
            name='familia',
            field=models.TextField(default='_'),
        ),
        migrations.AlterField(
            model_name='insecto',
            name='habitat',
            field=models.TextField(default='_'),
        ),
        migrations.AlterField(
            model_name='insecto',
            name='longitud',
            field=models.TextField(default='_'),
        ),
        migrations.AlterField(
            model_name='insecto',
            name='nombre',
            field=models.TextField(default='_'),
        ),
        migrations.AlterField(
            model_name='insecto',
            name='nomcientifico',
            field=models.TextField(default='_'),
        ),
        migrations.AlterField(
            model_name='insecto',
            name='numalas',
            field=models.TextField(default='_'),
        ),
        migrations.AlterField(
            model_name='insecto',
            name='orden',
            field=models.TextField(default='_'),
        ),
    ]
